// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_hourLabel;
extern lv_obj_t * ui_Conlon;
extern lv_obj_t * ui_MinuteLabel;
extern lv_obj_t * ui_SoilMoisteurTxt;
extern lv_obj_t * ui_Conlon1;
extern lv_obj_t * ui_SoilMoisteurPercent;
extern lv_obj_t * ui_SoilMonsteurBar;
extern lv_obj_t * ui_LightPercent;
extern lv_obj_t * ui_SoilMoisteurTxt1;
extern lv_obj_t * ui_HumidityPercent;
extern lv_obj_t * ui_Conlon2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
