// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_hourLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_hourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hourLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hourLabel, 40);
    lv_obj_set_y(ui_hourLabel, -50);
    lv_obj_set_align(ui_hourLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_hourLabel, "12");

    ui_Conlon = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Conlon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Conlon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Conlon, 51);
    lv_obj_set_y(ui_Conlon, -50);
    lv_obj_set_align(ui_Conlon, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Conlon, ":");

    ui_MinuteLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MinuteLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MinuteLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MinuteLabel, 65);
    lv_obj_set_y(ui_MinuteLabel, -50);
    lv_obj_set_align(ui_MinuteLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MinuteLabel, "30");

    ui_SoilMoisteurTxt = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SoilMoisteurTxt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoilMoisteurTxt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoilMoisteurTxt, -44);
    lv_obj_set_y(ui_SoilMoisteurTxt, -33);
    lv_obj_set_align(ui_SoilMoisteurTxt, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoilMoisteurTxt, "Soil Moisteur");
    lv_obj_set_style_text_font(ui_SoilMoisteurTxt, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Conlon1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Conlon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Conlon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Conlon1, -6);
    lv_obj_set_y(ui_Conlon1, -33);
    lv_obj_set_align(ui_Conlon1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Conlon1, ":");
    lv_obj_set_style_text_font(ui_Conlon1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilMoisteurPercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SoilMoisteurPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoilMoisteurPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoilMoisteurPercent, 14);
    lv_obj_set_y(ui_SoilMoisteurPercent, -33);
    lv_obj_set_align(ui_SoilMoisteurPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoilMoisteurPercent, "25%");
    lv_obj_set_style_text_font(ui_SoilMoisteurPercent, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilMonsteurBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_SoilMonsteurBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_SoilMonsteurBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_SoilMonsteurBar, 150);
    lv_obj_set_height(ui_SoilMonsteurBar, 10);
    lv_obj_set_x(ui_SoilMonsteurBar, 0);
    lv_obj_set_y(ui_SoilMonsteurBar, -17);
    lv_obj_set_align(ui_SoilMonsteurBar, LV_ALIGN_CENTER);

    ui_LightPercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LightPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightPercent, 47);
    lv_obj_set_y(ui_LightPercent, 0);
    lv_obj_set_align(ui_LightPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightPercent, "25%");
    lv_obj_set_style_text_font(ui_LightPercent, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoilMoisteurTxt1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SoilMoisteurTxt1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoilMoisteurTxt1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoilMoisteurTxt1, -25);
    lv_obj_set_y(ui_SoilMoisteurTxt1, 0);
    lv_obj_set_align(ui_SoilMoisteurTxt1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SoilMoisteurTxt1, "Luminous Intensity");
    lv_obj_set_style_text_font(ui_SoilMoisteurTxt1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityPercent = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_HumidityPercent, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_HumidityPercent, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_HumidityPercent, 150);
    lv_obj_set_height(ui_HumidityPercent, 10);
    lv_obj_set_x(ui_HumidityPercent, 0);
    lv_obj_set_y(ui_HumidityPercent, 17);
    lv_obj_set_align(ui_HumidityPercent, LV_ALIGN_CENTER);

    ui_Conlon2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Conlon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Conlon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Conlon2, 31);
    lv_obj_set_y(ui_Conlon2, 0);
    lv_obj_set_align(ui_Conlon2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Conlon2, ":");
    lv_obj_set_style_text_font(ui_Conlon2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}
